### ISSUE TITLE
Login Page Setup

### ISSUE THREAD

**Issue by skgupta507** [immdipu/Beatstreet#4]
How to make the Login And signup page work as i tried hosting it locally in my system but the login page gives error do i need add my .env variable in it to work. If so can u provide me with a Template of the .env file

**Comment by immdipu** [comment]
There is no env file. The issue might be related to the fact that the backend api  has CORS enabled. so you can't access backend locally or with any domain other than netlify.

**Comment by tejaramgv** [comment]
Bro how can I get access backend locally.. Please me bro

**Comment by immdipu** [comment]
I am going to  make the backend repo public soon.
